# Do not edit. Generated by the configure script.
export PATH:=/home/kxkivi/yh-peli/node-v16.13.1/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/home/kxkivi/.local
